### ISSUE TITLE
`stbt batch run` exit status should respect pass/failure/error status from built-in & user-supplied classify scripts

### ISSUE THREAD

**Issue by LewisHaley** [stb-tester/stb-tester#207]
This is so errors such as "Blackmagic card froze" or "Blackmagic card in use" are correctly reported as Errors/Yellow in stbt report.

**Comment by drothlis** [comment]
This also affects usage of `stbt batch run` in a Continuous Integration test system, where you want the exit status of `stbt batch` to specify a yes-or-no answer, and where you want test errors to be ignored (maybe unless *all* the testruns errored).

Currently I work around this with a script that calls `stbt batch run -1` with a single testcase at a time and collects the exit statuses, like this:

    any_successes=0
    any_failures=0
    any_errors=0
    for t in testcases; do
        stbt batch run -1 $t
        case "$?" in
            0) any_successes=S;;
            1) any_failures=F;;
            *) any_errors=E;;
        esac
    done
    case "$any_successes$any_failures$any_errors" in
        S00) exit 0;;
        S0E) exit 0;;
        *F*) exit 1;;
        00E) exit 2;;
        *)  echo "logic error: Unexpected status '$any_successes$any_failures$any_errors'" >&2;
            exit 2;;
    esac

**Comment by drothlis** [comment]
Closing. Irrelevant since #588.
