### ISSUE TITLE
VidiU: Tests fail with GStreamer error when the set-top-box under test is rebooted and --save-video is in use

### ISSUE THREAD

**Issue by szemate** [stb-tester/stb-tester#211]
**Description of the test**
- The set-top-box gets power-cycled.
- The test periodically attempts to enter the main menu. The test passes if it's possible to enter the main menu within 5 minutes from turning the power on.
- During boot-up the set top box displays two splash screens before getting back to live TV.
- The two splash screens have different resolutions, therefore the VidiU encoder restarts twice.

**Issues**

(1.) Running the test with `--save-video` and the following source pipeline:

```
source_pipeline = rtmpsrc location=rtmp://testaut-2-pc-1/live/testaut-2-stb-1\ live=1 ! decodebin ! videoscale ! video/x-raw,width=1280,height=720
```

results in the following GStremer error:

```
GStreamer error: negotiation problem.
gstvideoencoder.c(1368): gst_video_encoder_chain (): /GstPipeline:pipeline1/GstVP8Enc:vp8enc0:
encoder not initialized
```

Logs: https://github.com/szemate/stb-tester/blob/save-video-issue/logs/with-save-video-with-videoscale-without-videorate.log

(2.) Without `--save-video` the test is running happily.
Logs: https://github.com/szemate/stb-tester/blob/save-video-issue/logs/without-save-video-with-videoscale.log

(3.) Interestingly, with `--save-video` but without resizing the video:

```
source_pipeline = rtmpsrc location=rtmp://testaut-2-pc-1/live/testaut-2-stb-1\ live=1
```

there is no GStreamer error but the test fails with `NoVideo`.
Logs: https://github.com/szemate/stb-tester/blob/save-video-issue/logs/with-save-video-without-videoscale-without-videorate.log

(4.) I found a useful forum post[1] that recommended adding `videorate` to the source pipeline because the H.264 encoder doesn't like that the timestamps restart counting from zero when the source pipeline is rebuilt. Modifying the video saving pipeline as:

``` py
video_pipeline = (
    "t. ! queue leaky=downstream ! videorate ! videoconvert ! "
    "vp8enc cpu-used=6 min_quantizer=32 max_quantizer=32 ! "
    "webmmux ! filesink location=%s" % save_video)
```

eliminates the above errors, however, the saved video is useless as it only contains a few frames from before the box gets power-cycled.
Saved video: https://raw.githubusercontent.com/szemate/stb-tester/save-video-issue/logs/corrupted-video.webm
Logs: https://github.com/szemate/stb-tester/blob/save-video-issue/logs/with-save-video-with-videoscale-with-videorate.log

[1] http://gstreamer-devel.966125.n4.nabble.com/dynamic-pipeline-getting-not-negotiated-error-when-adding-filesink-tp4661824p4661825.html

**Configuration**

I was running the tests with:
- stb-tester 0.20
- Fedora 20
- Linux kernel 3.15.6-200
- GStreamer 1.2.4
- libvpx 1.3.0

My `stbt.conf`:

```
[global]
control = irnetbox:testaut-2-switch-pc.dev.youview.co.uk:1:/home/szemate/uitests/config/humax.irnetbox.conf
power_outlet = aten:testaut-2-pdu.dev.youview.co.uk:1
restart_source = False
sink_pipeline = xvimagesink sync=false
source_pipeline = rtmpsrc location=rtmp://testaut-2-pc-1/live/testaut-2-stb-1\ live=1 ! decodebin ! videoscale ! video/x-raw,width=1280,height=720
```

**Comment by wmanley** [comment]
Issue has been dormant for 6 years.  Closing.
