### ISSUE TITLE
Bad error message when matching non-BGR images

### ISSUE THREAD

**Issue by LewisHaley** [stb-tester/stb-tester#310]
```python
def _match(image, template, match_parameters, template_name):
    if any(image.shape[x] < template.shape[x] for x in (0, 1)):
        raise ValueError("Source image must be larger than template image")
    if any(template.shape[x] < 1 for x in (0, 1)):
        raise ValueError("Template image must contain some data")
    if template.shape[2] != 3:
        raise ValueError("Template image must be 3 channel BGR")
```

The final `if` causes an `IndexError` with single-channel images because the image `shape` is `(y, x)` not the assumed `(y, x, c)`. The result is that the purposefully placed error message about the required image types does not get raised.

**Comment by wmanley** [comment]
I guess that should read `if len(template.shape) != 3 or template.shape[2] != 3:`.  Do you have a test case?  How did you come across this issue?

**Comment by LewisHaley** [comment]
> Do you have a test case? How did you come across this issue?

I don't have a test case - I just was trying to get a fiddly bit of transparent navigation to work (which involved pre-processing frame and template) which resulted in passing in a greyscale (single channel) template into `stbt.match`. I think you could synthesise it with something like this:
```python
im = numpy.zeros(shape=(10, 10), dtype=numpy.uint8)
try:
    stbt.match(im)
except ValueError as e:
    assert "Template image must be 3 channel BGR" in str(e)
```

**Comment by drothlis** [comment]
Thanks for the bugreport @LewisHaley. I've raised #315 to fix this.
