### ISSUE TITLE
How to use python behave lib along with stbt

### ISSUE THREAD

**Issue by SatadruBhattacharjee** [stb-tester/stb-tester#416]
Hi, 
I would like to incorporate BDD style behave lib for writing the feature files. Is it possible to use behave Lib along with stbt.

Regards,
Sat

**Comment by drothlis** [comment]
I'm sure it's possible to get `behave` to spawn a subprocess and invoke `stbt run`. More granular integration will require support for importing stbt as a library -- see #297 "Librification".
