### ISSUE TITLE
use of apostrophes in error messages

### ISSUE THREAD

**Issue by rinaldomerlo** [stb-tester/stb-tester#427]
Maybe it's just me being a rubbish programmer, but the use of apostrophes in the stbt error messages like " Didn't find match for...." often causes us unnecessary headaches, for example when feeding the results data into php arrays. It would be better if these were all changed to "Did not". 

If you agree, I would like to do a pull-request to change this.

As far as I can see, the following would need to change:

> _stbt/core.py:        return "Didn't find match for '%s' within %g seconds." % (
> _stbt/core.py:        return "Didn't find motion%s within %g seconds." % (
> _stbt/core.py:            "Didn't meet precondition '%s' (original exception was: %s)"
> _stbt/core.py:        level, "Matched" if matched else "Didn't match",
> _stbt/core.py:          <td>{{"Matched" if matched else "Didn't match"}}</td>
> _stbt/core.py:          <td>{{"Matched" if m._first_pass_matched else "Didn't match"}}</td>
> stbt/android.py:    raise RuntimeError("AdbDevice: Didn't find display size in dumpsys output")
> stbt-camera.d/stbt_camera_calibrate.py:            print "Didn't understand command %r" % x
> tests/test-irnetbox.sh:        fail "Didn't receive IRNetBox ERROR"
> tests/test-irnetbox.sh:        fail "Didn't receive IRNetBox NACK"
> tests/test-irnetbox.sh:    cat log | grep -q timeout || fail "Didn't raise timeout"
> tests/test-match.sh:        || fail "Didn't see 'UITestError: No such template file'"
> tests/test-match.sh:        || fail "Didn't see 'ValueError: Template image must be 3 channel BGR'"
> tests/test-match.sh:        { cat test.log; fail "Didn't see exactly 1 keypress"; }
> tests/test-match.sh:        { cat test.log; fail "Didn't see exactly 3 keypresses"; }
> tests/test-stbt-auto-selftest.sh:        || fail "Didn't regenerate selftest"
> tests/test-stbt-batch.sh:    fail "Didn't find '$1' after 10 seconds"
> tests/test-stbt-batch.sh:        fail "Didn't find directory listing at '/'"
> tests/test-stbt-batch.sh:        fail "Didn't find index.html at '/my-test-session'"
> tests/test-stbt-batch.sh:        fail "Didn't find index.html at '/my-test-session/'"
> tests/test-stbt-py.sh:      echo "error: Didn't find 'Cue Point' in $scratchdir/webminspector.log"
> tests/test-stbt-run.sh:        "PreconditionError: Didn't meet precondition 'Tune to gamut pattern'" \

and possibly also this?..

> vendor/py-lmdb/lmdb/cpython.c:        type_error("Won't implicitly convert Unicode to bytes; use .encode()");

**Comment by wmanley** [comment]
Hi @rinaldomerlo 

This isn't a change that would be acceptable upstream.  I don't know any PHP or how you're processing the output from stbt, but I would recommend looking for a function that can take an input with quotes and do proper escaping of the result.  This will make your system more robust to any input it's fed as you may not be able to predict now that no-one will ever try to feed an error message with quotes into it.

Be aware that error messages can also include newlines and other special characters.  It's worth checking that your system is robust to things of that nature too.
