### ISSUE TITLE
multiple lirc instances

### ISSUE THREAD

**Issue by jamenlang** [stb-tester/stb-tester#465]
I've got two lirc servers in my house, one upstairs and one downstairs, they both have ir blasters to control tvs and dvd/blu ray players, is there a way to have one of them rebroadcast ir commands to the second so i can set my client to control both of them and their respective devices?

client -> command -> server 1 -> ir blaster 1 & server 2 -> ir blaster 2

I thought this could be accomplished with --listen and --connect but i can't get it to work as I imagined.

**Comment by drothlis** [comment]
Hi @jamenlang 

For general help please use the stb-tester mailing list:
stb-tester@googlegroups.com ([Archive](http://groups.google.com/group/stb-tester))

If you want both IR transmitters on the same host see [How to use multiple LIRC infra-red transceivers] on our wiki. If you have trouble maybe try the lirc mailing list.

If you want them on different hosts see [stbt-control-relay] which can multiplex to multiple lirc servers over TCP.

[How to use multiple LIRC infra-red transceivers]: https://github.com/stb-tester/stb-tester/wiki/How-to-use-multiple-LIRC-infra-red-transceivers
[stbt-control-relay]: https://github.com/stb-tester/stb-tester/blob/master/stbt_control_relay.py
