### ISSUE TITLE
`stbt batch run` should check that all specified test files exist before running

### ISSUE THREAD

**Issue by LewisHaley** [stb-tester/stb-tester#51]
`runner/run` does not consider a test no existing ("IOError: [Errno 2] No such file or directory") an interesting failure, `runner/run -k` does not exit. Really, we don't want `runner/run -kk` (keep running regardless of _any_ failures) to continue running either, so runner should check that all test paths are accurate before starting.

**Comment by drothlis** [comment]
Closing. Irrelevant since #588.
