### ISSUE TITLE
How to import "stbt" and its functions into PyCharm?

### ISSUE THREAD

**Issue by mattissf** [stb-tester/stb-tester#577]
Hi

Maybe I am missing something obvious, but I can not for the life of me figure out how to import "stbt" properly into my PyCharm test-pack project.

![image](https://user-images.githubusercontent.com/152450/53549898-b8213400-3b35-11e9-8d51-2bf9bd541098.png)

How should I do this?

**Comment by msiden** [comment]
A simple "import stbt" should definitely work. If it doesn't I figure there must be something wrong with your installation or your environment. Have you checked your Pythonpath?

**Comment by mattissf** [comment]
I think my problem is that I use a project based off of "stb-tester-test-pack" that does not include "stbt" as a library. I don't have STB tester installed locally, since I use pipenv, and I don't think this library is available on pypi.org?

I ended up unpacking release 29 of stb-tester and just adding it as a source folder in my PyCharm project. That seemed to work.

**Comment by mattissf** [comment]
I will close this ticket here, thanks for the help!
