### ISSUE TITLE
IRNetBox returned message IR_ASYNC_COMPLETE

### ISSUE THREAD

**Issue by demorph** [stb-tester/stb-tester#655]
Hi , we've been using the irnetproxy script provided by stestagg on "https://github.com/stestagg/irnetproxy" since the irnetbox can't handle multiple TCP connections , but we keep getting "IRNetBox returned message IR_ASYNC_COMPLETE" exception .
Any clarification on the subject ?
Best regards .

**Comment by wmanley** [comment]
Try asking in the repo you linked.
