### ISSUE TITLE
I am falling in following errors...

### ISSUE THREAD

**Issue by Azaretdodo** [stb-tester/stb-tester#674]
Hello,

I have run 'python setup.py install' for happening Following errors :

![image](https://user-images.githubusercontent.com/30596513/82731140-06a38b00-9d05-11ea-9a50-092ec2c0ace2.png)

Thank you in advance to repair the errors,

I am installing libxml2,

Regards.

Azaretdodo.

**Comment by wmanley** [comment]
This is the github repo for stb-tester.  Try asking libxml2 people if you're having problems with libxml2
