### ISSUE TITLE
stbt.find_selection_from_background is not available

### ISSUE THREAD

**Issue by Witos** [stb-tester/stb-tester#748]
According to docs https://stb-tester.com/manual/python-api#stbt-find-selection-from-background stbt.find_selection_from_background function should be available in stbt starting from version 32. I cannot find it anywhere though - it's not available after import stbt-core in python. I grepped the code and there is nothing (https://github.com/stb-tester/stb-tester/search?q=find_selection_from_background). Where I can find this function?

**Comment by wmanley** [comment]
`find_selection_from_background` is only available to customers using the stb-tester HDMI node.  See https://stb-tester.com/ for more information.
