### ISSUE TITLE
stb-tester not stable on Debian 12

### ISSUE THREAD

**Issue by rinaldomerlo** [stb-tester/stb-tester#843]
This isn't really a bug report as I believe you only certify stb-tester on Ubuntu 22 anyway, but you may want to know, that when using stb-tester on Debian (12) it fails to put the gstreamer pipline into playing state about 50% of the time.

I've attached a verbose log below, as well as two gstreamer pipeline graphs showing the difference between when it works and when it doesn't.

[console_output.txt](https://github.com/user-attachments/files/17949235/console_output.txt)
![bad_082761784](https://github.com/user-attachments/assets/a9e48967-ddb3-452b-9072-dca770092ad8)
![good](https://github.com/user-attachments/assets/8f870225-edca-4eca-8caa-c1a462bb6f83)

It's not a gstreamer issue as far as I can tell, because gst-launch-1.0 is rock solid, whereas stbt_run.py is not. 

I had the same issue on two independent PC's, a dell desktop with a blackmagic 4k intensity pro, and a broadberry server with a blackmagic quad hdmi, before I tried going back to Ubuntu 22 (which fixed the issue on both). So I'm fairly sure you will find it 100% reproducible on any setup running Debian.

**Comment by drothlis** [comment]
Sounds like an issue with the Blackmagic driver, decklinksrc, and/or the caps in your pipeline.
