### ISSUE TITLE
[low priority] save_video=False should *not* save "False.webm"

### ISSUE THREAD

**Issue by LewisHaley** [stb-tester/stb-tester#97]
If your stbt.conf has `save_video=[anything]` and you want to _not_
save a video for a specific `stbt run` call, the way to turn save_video
is to put `save_video=` (i.e. completely blank). `save_video=False`
results in "False.webm". It would be less
confusing if these were valid options:
`save_video=True` : save "video.webm" ϟ
`save_video=False` : don't save a video
`save_video=[anything else]` : save [anything else].webm (as it currently is)

ϟ Or maybe "[name of test].webm"?

**Comment by drothlis** [comment]
I'm tempted to close this issue and solve it by writing proper documentation for `stbt.conf`.

**Comment by wmanley** [comment]
Noone's touched this in 5 years, Closing.
